version: '3'

services:

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm

    volumes:
      - ./:/app
    working_dir: /app

  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # Создаваемая по умолчанию бд
      MYSQL_DATABASE: paradam
      # Линкуем внешнюю папку для хранения БД
    volumes:
      - ./database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mysql
