# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  default:
    - step:
        name: Deploy to test
        deployment: test
        script:
          - pipe: atlassian/sftp-deploy:0.5.3
            variables:
              USER: 'andrii'
              SERVER: '46.219.56.21'
              REMOTE_PATH: '/var/www/paradam.acer'
              LOCAL_PATH: './' # Optional.
              # SSH_KEY: '<string>' # Optional.
              # PASSWORD: '<string>' # Optional.
              # EXTRA_ARGS: '<string>' # Optional.
              # DEBUG: '<boolean>' # Optional.
 
