pipelines:
  custom: # Pipelines that can only be triggered manually
    sonar:
      - step:
          script:
            - echo "Manual triggers for Sonar are awesome!"
            - pipe: atlassian/ssh-run:0.2.3
              variables:
                SSH_USER: $USER_REMOTE
                SERVER: '46.219.56.21'
                MODE: 'command'
                COMMAND: './remote-script.sh'

    deployment-to-prod:
      - step:
          script:
            - echo "Manual triggers for deployments are awesome!"
  branches:  # Pipelines that run automatically on a commit to a branch can also be triggered manually
    staging:
      - step:
          script:
            - echo "Automated pipelines are cool too."